newrelic/nri-kube-events

- .github/workflows/release.yml
Username and Token were inverted
> fix(ci/cd): we were sending username instead of token

- .github/workflows/release.yml
> ci: ensure deployed yaml points to version being released

- .github/workflows/nightly.yml
- .github/workflows/push_pr.yml
- .github/workflows/release.yml
- .github/workflows/security.yml
As part of nightlies images effort this commit adds a nightly workflow
for GitHub Actions, which will build the integration Docker image daily
and publish it under a 'nigtly' tag, which will be automatically pulled
by staging clusters.
Refs https://github.com/newrelic/newrelic-coreint/issues/130
Signed-off-by: Mateusz Gozdek <mgozdek@microsoft.com>
> .github/workflows/nightly.yml: initial commit

- Dockerfile
Ignoring the automatic PR to pin minor version
> Bump alpine Version

- cmd/nri-kube-events/main.go
- pkg/sinks/sinks.go
Fix https://github.com/newrelic/nri-kube-events/issues/27
> feat(log): remove redundant newline in log text

- charts/nri-kube-events/Chart.lock
- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/README.md
- charts/nri-kube-events/templates/NOTES.txt
- charts/nri-kube-events/templates/_helpers.tpl
- charts/nri-kube-events/templates/_helpers_compatibility.tpl
- charts/nri-kube-events/templates/deployment.yaml
- charts/nri-kube-events/tests/images_test.yaml
- charts/nri-kube-events/values.yaml
I changed the `image` map to `images` to align with other helm charts and completely forgot to add a compatibility layer for the people that are upgrading.
This should solve the issue.
> Add compatibility layer

- CHANGELOG.md
- Dockerfile
- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/README.md
- charts/nri-kube-events/tests/images_test.yaml
- charts/nri-kube-events/values.yaml
- pkg/events/router.go
- pkg/events/router_test.go
Relates to https://github.com/newrelic/helm-charts/issues/845.
Fix url to point to the proper branch and some codespell errors.
> Fix helm chart url

- README.md
> chore: Update the community plus header

- .github/workflows/push_pr.yml
Update the matrix to test against new k8s versions.
Also make sure python is setup for the chart testing action.
> Update test matrix

- cmd/nri-kube-events/main.go
This func never returns an error.
> Fix lint error

- .github/workflows/push_pr.yml
Signed-off-by: Vihang Mehta <vmehta@newrelic.com>
> Remove manual go cache since setup-go/v4 automatically caches

- skaffold.yaml
- skaffold_build.sh
The docker-push make target was removed. So update the script to manually push the image.
> Fix skaffold build script

- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/README.md
update readme by `helm-docs`
bump versions
> Bump Chart Versions

- .github/workflows/push_pr.yml
- CHANGELOG.md
Fix K8s Version Format
For example, "1.24.17" -> "v1.24.17"
> Fix K8s Version Format

- .github/workflows/changelog.yml
Implements NR-157560.
Update changelog.yml to follow the same pattern as the one on repo [k8s-metadata-injection repo](https://github.com/newrelic/k8s-metadata-injection/blob/main/.github/workflows/changelog.yml)
> feat(workflows): Update changelog workflow to look like the one on `k8s-metadata-injection` repo

- .github/renovate.json5
- .github/workflows/push_pr.yml
- .github/workflows/release.yml
- .github/workflows/security.yml
- .github/workflows/trigger_prerelease.yml
- .gitignore
- Makefile
Addresses NR-157561
Updates the repo's workflows to allow for automatic release
> feat: Enable automatic release

- .github/workflows/push_pr.yml
- .github/workflows/release.yml
- src/utils/version-update.go
Addresses NR-157563
Automates the version bump for both the Docker image and the Helm chart
Please delete options that are not relevant.
> feat(ci): Automate version bumps

- .github/workflows/release.yml
> fix(ci): Fix typo

- CHANGELOG.md
Adding changelog entry that was missing in #293
Please delete options that are not relevant.
> fix(ci): Update changelog for PR 293

- .github/workflows/release.yml
- CHANGELOG.md
Fixes typos in a job step for workflow `release.yml`
> fix(ci): Fix `release.yml` workflow

- .github/workflows/changelog.yml
Allow to rerun workflow when labels change. That allows someone who forgot to add the skip label to force the check to be run - and get ignored
> Run checklog workflow when labels change

- .github/workflows/changelog.yml
There is a corner case where the changelog workflow is running and thinking there are changes the file when there are not.
> Add debugging information to the workflow

- .github/workflows/changelog.yml
Make changelog.yml workflow run when labels change
> Make changelog.yml workflow run when labels change

- .github/workflows/release.yml
- CHANGELOG.md
> Update GITHUB_TOKEN permissions to allow for job to open a PR

- .github/workflows/release-chart.yml
- CHANGELOG.md
Allow workflow to release Helm chart
> fix: Update GITHUB_TOKEN permissions

- .github/workflows/security.yml
Reduce redundant code and simplify code maintenance by making the security workflow reusable.
> ci: Update 'Security Scan' to use reusable workflow

- .github/workflows/trigger_prerelease.yml
Update 'Trigger prerelease creation' to use reusable workflow
> ci: Use reusable workflow for 'Trigger prerelease creation'

- .github/workflows/nightly.yml
> ci: Update Slack notifications

- .github/workflows/push_pr.yml
Updating minikube version so Helm chart linting works for Kubernetes v 1.27
> ci: Update minikube version

- .github/workflows/push_pr.yml
- CHANGELOG.md
> chore: Remove 1.23 support

- .github/workflows/push_pr.yml
- CHANGELOG.md
> chore: Add k8s v1.28.0-rc.1 support

- .github/workflows/push_pr.yml
Disabling [semgrep action that has been deprecated](https://github.com/returntocorp/semgrep-action)
> fix: Disable semgrep action that has been deprecated

- .github/renovate.json5
Add customManager for renovate to bump dependencies in the values.yaml file.
> fix: Add custom manager

- .github/renovate.json5
Update renovate file to extend the renovate file from metadata-injection repo
> fix: Update renovate file 

- .github/workflows/push_pr.yml
- CHANGELOG.md
> chore: Replace k8s v1.28.0-rc.1 with k8s 1.28.3 support

- .github/workflows/changelog.yml
- .github/workflows/release-chart.yml
- .github/workflows/release-integration.yml
- .github/workflows/security.yml
- .github/workflows/trigger_prerelease.yml
- CHANGELOG.md
Update reusable workflow dependency
> feat: Update reusable workflow dependency

- .github/workflows/push_pr.yml
> chore: Update artifact action

- .github/workflows/push_pr.yml
- CHANGELOG.md
- Makefile
- README.md
> ci: add codecov

- .github/workflows/push_pr.yml
> chore: update codecov config

- .github/renovate.json5
Updating Renovate config so we have automated updates for `k8s-events-forwarder` in `nri-kubernetes` and `nri-kube-events` (moving configuration to base config)
> chore: Update renovate config

- .github/workflows/nightly.yml
- .github/workflows/release-integration.yml
> chore: Update secrets

- CHANGELOG.md
- charts/nri-kube-events/templates/deployment.yaml
- charts/nri-kube-events/tests/deployment_test.yaml
> feat: add linux node selector

- README.md
- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/README.md
> chore: Update bug bounty program + owners
