newrelic/nri-kube-events

- .github/workflows/release.yml
- CHANGELOG.md
- deploy/nri-kube-events.yaml
`DOCKER_IMAGE_NAME` was missing when pushing latest version image.
I refactored the code a bit to show that the variable is used in the makefile only and it is not needed afterwards
> fix(cicd): missing environment variable

- .github/workflows/helm.yml
Job analogous to [nri-prometheus](https://github.com/newrelic/nri-prometheus/blob/main/.github/workflows/helm.yml)', which creates a PR bumping the `appVersion` of the helm chart associated to this repo in [helm-charts](https://github.com/newrelic/helm-charts).
> bump helm chart on release

- .github/workflows/release.yml
- CHANGELOG.md
- Makefile
- cmd/nri-kube-events/main.go
- pkg/sinks/new_relic_infra.go
- pkg/sinks/new_relic_infra_test.go
- pkg/sinks/sinks.go
- pkg/sinks/stdout.go
- pkg/sinks/testdata/new_relic_infra_test_data.json
- test/integration/test_agent_sink.go
The integration was populating as well a not-standard `newRelicEventrouterVersion` adding  it to the sample.
There is no use-case from my point of view to keep a different version just for that. However I kept the attribute simply populating it with integration version.
Please notice that no integrationVersion or integrationName is populated
```
"events": [
{
"category": "kubernetes",
"clusterName": "coreint-canary-gcp-standard",
"eventRouterVersion": "1.6.0",
[...]
},
```
Fix https://github.com/newrelic/nri-kube-events/issues/26
> fix(ciCD): populate automatically integration version

- go.mod
- go.sum
Fix `go.etcd.io` vulnerability issue.
We got some pipelines failing like this [one](https://github.com/newrelic/nri-kube-events/runs/6026162996?check_suite_focus=true) because of a recent vulnerability found in a package apparently used by an indirect dependency.
Vulnerability details: https://nvd.nist.gov/vuln/detail/CVE-2018-1098
> fix: update go.etcd.io pinged version to fix CVE-2018-1098 vulnerability

- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/templates/_helpers.tpl
- charts/nri-kube-events/templates/agent-configmap.yaml
- charts/nri-kube-events/templates/configmap.yaml
- charts/nri-kube-events/templates/deployment.yaml
- charts/nri-kube-events/tests/agent_configmap_test.yaml
- charts/nri-kube-events/tests/configmap_test.yaml
- charts/nri-kube-events/tests/deployment_test.yaml
- charts/nri-kube-events/values.yaml
While preparing the documentation for this chart I realized that the helper from the common library for the agent's config map was not being used.
So I raised a couple of inconsistencies with the other reference chart (`nri-kubernetes`) and added a couple of tests.
> Align values.yaml with `nri-kubernetes` and use the agent helper

- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/README.md
- charts/nri-kube-events/templates/_helpers_compatibility.tpl
- charts/nri-kube-events/values.yaml
Running with helm 3.5.4
Before
```
/Users/pgallina/Downloads/darwin-amd64/helm template ./charts/nri-kube-events --set cluster=asd --set licenseKey=asd
Error: parse error at (nri-kube-events/templates/_helpers_compatibility.tpl:231): unclosed action
Use --debug flag to render out invalid YAML
```
After
```
/Users/pgallina/Downloads/darwin-amd64/helm template ./charts/nri-kube-events --set cluster=asd --set licenseKey=asd
---
[...]
```
> fix(chart): newline cause issues for old helm versions

- .github/renovate.json5
- charts/nri-kube-events/Chart.lock
- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/templates/deployment.yaml
- charts/nri-kube-events/values.yaml
We were using `labels` instead of `podLabels` in the pods so we were not leveraging the `common-library` properly.
Fixes newrelic/nri-kube-events#142
> [chart] Fix `podLabels`

- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/ci/test-bare-minimum-values.yaml
- charts/nri-kube-events/templates/_helpers_compatibility.tpl
- charts/nri-kube-events/tests/images_test.yaml
There are issues with `nri-bundle` while trying to merge it and it seems that there are issues in this chart. I put a screenshot in case the workflow logs rotate:
The test I added in this PR failed with this before fixing it:
```
FAIL  test image compatibility layer   tests/images_test.yaml
- by default the tag is not nil
- asserts[0] `notMatchRegex` fail
Template:       nri-kube-events/templates/deployment.yaml
DocumentIndex:  0
Path:   spec.template.spec.containers[0].image
Expected NOT to match:
.*nil.*
Actual:
newrelic/nri-kube-events:%!s(<nil>)
```
Then I added the default filter to default to `appVersion` in case there is no tag defined.
> [chart] Add tests for empty tag and fix it

- .github/workflows/push_pr.yml
This follows this [guide](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) to update they way outputs are set. This should silence some of the workflow warnings.
> chore: Use new github output workflow commands

- .github/dependabot.yml
There are a bunch of stale dependencies that haven't been upgraded. Incresing the dependabot limits should help up address all of these upgrades quicker.
> chore: Increase dependabot limits

- go.mod
These deps no longer exist in our go.mod or go.sum and hence we don't need the corresponding replace directives.
> chore: Remove unused gomod replace directives

- cmd/nri-kube-events/config.go
- cmd/nri-kube-events/config_test.go
- cmd/nri-kube-events/main.go
- pkg/sinks/new_relic_infra.go
- pkg/sinks/new_relic_infra_test.go
- pkg/sinks/sinks.go
- pkg/sinks/stdout.go
- test/integration/integration_test.go
- test/integration/test_agent_sink.go
Use the `-local` flag to reformat all the go imports
> chore: reformat all goimports

- .github/workflows/repolinter.yml
Update the action and the corresponding script. This should be the last of the actions running on deprecated node12.
> chore: bump actions/github-script from 4.1 to 6

- Makefile
- deploy/local.yaml.example
- skaffold.yaml
- skaffold_build.sh
This does a handful of things things:
- Runs the skaffold fix command to upgrade the skaffold file to be compatible with new versions of skaffold.
- Update the skaffold, docker and makefile setup to ensure that skaffold dev and skaffold run do the correct thing and deploy a dev app.
- Updates the local deployment to use a dev namespace instead of the default namespace so that it is easier to cleanup all the dev resources.
This should help with future dev and debug efforts.
> Upgrade and fixup skaffold deploys

- cmd/nri-kube-events/config.go
- cmd/nri-kube-events/main.go
- go.mod
- pkg/sinks/new_relic_infra.go
- pkg/sinks/sinks.go
- pkg/sinks/stdout.go
github.com/pkg/errors has been archived and the go stdlib supports error wrapping and unwrapping natively. So switch to using the stdlib way of handling errors.
> Use native error wrapping

- pkg/common/objects.go
- pkg/events/router.go
- pkg/events/router_test.go
- pkg/events/sink.go
- pkg/sinks/new_relic_infra.go
- pkg/sinks/new_relic_infra_test.go
- pkg/sinks/stdout.go
- test/integration/test_agent_sink.go
KubeEvent is a shared API between the data we get from the Informers and the
data we send to the sinks.
Since the event routers and sinks should be separate packages and we are working
towards that goal, pulling KubeEvent into a common package that is shared helps
make the API cleaner.
In the future we might add KubePod, KubeNode etc as we write informers that send
data based on other k8s objects.
> Move KubeEvent to common package

- .golangci.yml
- cmd/nri-kube-events/config.go
- cmd/nri-kube-events/main.go
- pkg/events/router_test.go
- pkg/sinks/new_relic_infra.go
- pkg/sinks/new_relic_infra_test.go
- pkg/sinks/sinks.go
- test/integration/test_agent_sink.go
Add a local config so that IDEs can report lint issues. Otherwise lint issues
are not detected until actions are run.
Also run the lint autofixer to fix common issues.
> Add a local golangci-lint config and autofix fixable issues

- .github/ct.yaml
This makes it easier to make changes to the helm chart
values without needing to also bump the version in the
same PR.
> Update ct linter to not check for version bumps

- .github/workflows/release-chart.yml
Since chart releaser triggers on ever push to main, we need this
flag now that we allow bumping chart details without bumping
the chart version (https://github.com/newrelic/nri-kube-events/pull/199). This prevents the releaser from trying to overwrite
an existing release and failing.
> Tell chart releaser to skip existing charts

- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/templates/deployment.yaml
- charts/nri-kube-events/values.yaml
A customer found that the resource settings for kube-events' forward sidecar is not generated (https://github.com/newrelic/nri-kube-events/issues/186) although the resource is set for the pod in values.yaml
I make up the resource setting section for the kube-events' forward sidecar
build the helm chart change locally and run
`nri-bundle %  helm template nrk8s ./ --values /Users/xqi/Documents/GitHub/helm-charts/values.yaml  --dry-run >> ~/Desktop/new.yaml `
The generated yaml
```
containers:
- name: kube-events
...
- name: forwarder
...
resources:
limits:
cpu: 300m
memory: 500Mi
requests:
cpu: 100m
memory: 128Mi
```
> Add Resource Settings for Kube-events' Forwarder

- charts/nri-kube-events/Chart.yaml
- charts/nri-kube-events/README.md
Changes:
- Bump app version to recently released `v1.9.2`
- Bump chart version
- Update `README` using `helm-docs`.
> Bump chart version and update maintainers

- .github/workflows/push_pr.yml
This is a followup to #208 
buildkit doesn't load images by default since it might be building multiple platforms. So we need to explicitly tell buildkit to load the image so that minikube can find it later. 
Signed-off-by: Vihang Mehta <vmehta@newrelic.com>
> Load docker image when building

- Dockerfile
Copying the go.mod and go.sum first and manually downloading deps
means that another layer will be created that will be cached
separately from the rest of the source code. This should speed up builds.
Signed-off-by: Vihang Mehta <vmehta@newrelic.com>
> Reorganize docker build for better layer caching

- .github/workflows/push_pr.yml
`minikube load image` seems to silently fail when the image path is wrong.
This fixes the path and includes a `minikube image ls` to check that the loaded image now exists.
> Fix image download and load

- .github/workflows/push_pr.yml
Fixes: https://github.com/newrelic/nri-kube-events/actions/runs/4683262761/jobs/8298149558?pr=223
Now that https://github.com/helm-unittest/helm-unittest/pull/114 has made Helm3 support the default, we no longer need to specify Helm3.
> Fix push_pr workflow

- .golangci.yml
- pkg/common/utils.go
- pkg/common/utils_test.go
- pkg/sinks/new_relic_infra.go
- pkg/sinks/new_relic_infra_test.go
Moves flattenStruct into the common package under utils and also adds a helper to split strings based on length without splitting runes.
> Add common utils

- cmd/nri-kube-events/main.go
- go.mod
- pkg/sinks/new_relic_infra.go
This ensures that even when all scrapers are disabled, the prometheus
server adds to the workgroup and keeps the integration running.
While this is a strange mode to run this scraper in (i.e. with all data
collection disabled), this ensures that the pod doesn't crashloop in
such a scenario due to it exiting.
> Change prometheus serving to also use the workgroup and close channel

- .github/workflows/push_pr.yml
- CHANGELOG.md
The K8s versions in E2e Tests are old.
Check the GitHub workflows that run for PR pushes and:
Remove any references to Kubernetes versions 1.22 or older
Add to tests Kubernetes versions: 1.23.17, 1.24.17, 1.25.13, 1.26.8, 1.27.5
The --container-runtime flag was deprecated in k8s 1.24, and removed in k8s 1.27
So the e2e test for 1.27.5 with minikube fails
https://github.com/kubernetes/minikube/issues/16112
https://github.com/kubernetes/minikube/pull/16124
So I make the change `start args: "--nodes=2 --container-runtime=${{ matrix.cri }}"` which is learned from `nri-kubenetes` repo
> Update K8s Versions in E2E tests

- .github/workflows/push_pr.yml
Workflow `push_pr` is the only workflow that does not use a GitHub runner with `ubuntu-latest`. This PR makes all workflows run on the same environment.
Please delete options that are not relevant.
> fix(ci): Make GitHub runner consistent on all workflows

- .golangci.yml
- CHANGELOG.md
> fix: Update linters and remove unused linters
